version: '3.8'

services:
  prjemian:
    image: prjemian/synapps:latest  # Use the same image as your script
    container_name: ioc13SIM1  # Match the naming convention from iocmgr.sh
    ports:
      - "5064:5064"  # EPICS CA server port
      - "5065:5065"  # EPICS CA repeater port
    environment:
      - "PREFIX=13SIM1:"
    networks:
      - epics-network
    stdin_open: true
    tty: true
    volumes:
      - ./tmp/ioc13SIM1/tmp:/tmp  # Mount temp directory like iocmgr.sh does
    command: bash -c "bash /root/bin/adsim.sh start && tail -f /dev/null"

  ophyd-websocket:
    build:
      context: ./ophyd-websocket
      dockerfile: Dockerfile
    container_name: ophyd-ws-server
    ports:
      - "8000:8000"
    environment:
      - "EPICS_CA_ADDR_LIST=prjemian"
      - "EPICS_CA_AUTO_ADDR_LIST=NO"
      - "EPICS_CA_MAX_ARRAY_BYTES=16777216"  # Often needed for EPICS
    depends_on:
      - prjemian
    networks:
      - epics-network

  frontend:
    build:
      context: ./finch
      dockerfile: Dockerfile
    container_name: finch-frontend
    ports:
      - "5173:5173"
    depends_on:
      - ophyd-websocket
    networks:
      - epics-network

networks:
  epics-network:
    driver: bridge
